# -*- coding: utf-8 -*-
"""colab & python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WknnTqu6WZrTHmqRgf6arbuz36UxDWgm
"""



# colab & python
import numpy as np
print("np version= {}.format(np.__version__)")
import matplotlib as mpl

print("mpl version={}".format(mpl.__version__))
import matplotlib.pyplot as plt # importing matplotlib
import pandas as pd

print("pd version= {}".format(pd.__version__))

from mpl_toolkits.mplot3d import Axes3D # import Axes3D, 3D plot

fig = plt.figure() # create a figure object
ax = Axes3D(fig) # defining 3d figure ax
x = np.arange(-4, 4, 0.25) # defining x
Y = np.arange(-4, 4, 0.25) # defining Y
x,Y = np.meshgrid(x, Y)
R = np.sqrt(x ** 2 + Y ** 2)
z = np.sin(R)
ax.plot_surface(x, Y, z, rstride=1, cstride=1, cmap=plt.cm.hot) # plot
ax.contourf(x, Y, z, zdir='z', offset=-2, cmap=plt.cm.hot)
ax.set_zlim(-2, 2) #set z-axes limit
plt.show()
#show plot